server:
  port: 8082

spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-processors
  datasource:
    url: jdbc:postgresql://localhost:5434/logging
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

app:
  kafka:
    topic: logs.ingested
    dlq-topic: logs.dlq
  cache:
    recent-logs-limit: 100
    ttl-hours: 1
  idempotency:
    ttl-hours: 24
  retry:
    max-attempts: 3
    initial-interval-ms: 1000
    multiplier: 2.0
    max-interval-ms: 10000

logging:
  level:
    com.logging: DEBUG
    org.springframework.kafka: WARN
