server:
  port: 8082

spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-processors

app:
  kafka:
    topic: logs.ingested

logging:
  level:
    com.logging: DEBUG
    org.springframework.kafka: WARN
